name: comment

on:
#  pull_request_review:
#    types: [submitted, edited]
  issue_comment:
    types: [created]


jobs:
  comment-echo:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'RTFT') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comment job"
