name: comment

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  comment-echo:
    if: ${{ contains(github.event.comment.body, 'RTFT') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comment job"
