name: comment

on:
  pull_request_review:
    types: [submitted]
#  issue_comment:
#    types: [created]


jobs:
  comment-echo:
    # use with pull_request_review
    # github.event.pull_request
    if: ${{ contains(github.event.review.body, 'RTFT') }}

#    works with issue_comment
#    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'RTFT') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comment job"
