name: comment

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  comment-echo:
    if: ${{ (github.event.pull_request.base.ref == 'main') && (contains(github.event.comment.body, 'RTFT')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comment job"
