name: comment

on:
  issue_comment:
    types: [created]

jobs:
  comment-echo:
    if: ${{ (github.event.issue.pull_request == 'true') && (contains(github.event.comment.body, '@RTFT')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comment job"
