name: release

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches: ['main']
  push:
    branches: ['main']

jobs:
  release-echo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "release job"
