name: release

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches: ['main']

jobs:
  release-echo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "release job"
  release-ct:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@release'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: echo "release!"
        if: steps.check.outputs.triggered == 'true'